### ISSUE TITLE
能否为某个Swift函数提供anti-fishhook功能？

### ISSUE THREAD

**Issue by Anthony-GitHub** [TannerJin/anti-fishhook#5]
请问是否有办法为swift代码中的某个函数提供anti-fishhook功能？

例如 HookMe 类中有静态方法和非静态方法：
```
class HookMe {
  public func log(_ msg: String) {
    print("HookMe log: " + msg)
  }
  
  public static func staticMethod() {
    print("Static method OK.")
  }
}
```

是否有有办法为这两个函数提供resetSymbol 功能？类似于：

```
resetSymbol(HookMe.log)
resetSymbol(HookMe.staticMethod)
```

按照现有的代码，好像是需要知道Swift命名重整（name mangling）后的函数名。但是在代码里无法提前知道命名重整后的函数名。

**Comment by TannerJin** [comment]
1. xcrun nm -a A.dylib 可以查看A.dylib的Swift  name mangling之后的符号。
2. 你的HookMe中的静态函数在A.dylib中，然后在B.dylib中调用该静态函数就可以在调用前使用resetSymbol功能。(fishhook针对外部符号)

**Comment by Anthony-GitHub** [comment]
谢谢，明白了。
