### ISSUE TITLE
可否针对常用的几个反调试的C函数写一下Anti-fishhook

### ISSUE THREAD

**Issue by sunqingquan** [TannerJin/anti-fishhook#6]
如题，反调试经常会用到如 ptrace，dlsym，sysctl，syscall，isatty  ，但是黑客经常使用fishhook 来替换这几个方法，可否写一下这几个函数的anti-fishhook写法，谢谢了

**Comment by TannerJin** [comment]
FishHookChecker.denyFishHook("dlsym")
