### ISSUE TITLE
iOS 15 中的已经没有 dyld_info，需要改为从 dyld_chained_fixup 中取信息 

### ISSUE THREAD

**Issue by LucasXu0** [TannerJin/anti-fishhook#7]
😁

**Comment by p-x9** [comment]
Following is a swift implementation of `dyld_chained_fixups` parse.
https://github.com/p-x9/MachOKit/blob/main/Sources/MachOKit/MachOImage%2BDyldChainedFixups..swift

I have tried to implement anti-fishhook using information from dyld_chained_fixups in the following repository.
https://github.com/p-x9/swift-anti-fishhook
